### ISSUE TITLE
Thiner scroll bars

### ISSUE THREAD

**Issue by lgk-bsw** [bruegmann/blue-react#24]
Change it to something like this:
```css
@media screen and (min-width: 768px) {
    ::-webkit-scrollbar {
        height: 10px;
        width: 10px;
    }
}
```
