### ISSUE TITLE
Make long error messages not flow to top

### ISSUE THREAD

**Issue by lgk-bsw** [bruegmann/blue-react#26]
Add something like this:
```css
.blue-app-status-alert {
    max-height: calc(100vh - 15rem);
    overflow-y: auto;
}
```
