### ISSUE TITLE
Rounded Search in Sidebar and add margin

### ISSUE THREAD

**Issue by lgk-bsw** [bruegmann/blue-react#29]
Add something like this:
```css
.blue-app-search {
    border-radius: 4px;
    margin: 0 4px;
}
```
